public class HomeworkPractice {
    public static void show() {
        List<integer>mylist=new List<integer>{10,20,30,40,50};
            integer max =636252189;
        mylist.add(max);
        mylist.sort();
        integer index=mylist.indexOf(max);
        mylist.remove(index);
        index--;
        while(index>=0){
            system.debug(mylist.remove(index));
            index--;
        }

        
        
        
        
        
        
        
        
        
       /* Map <String, Decimal>myMap= new Map <String,Decimal>();
        myMap.put('Book', 9.50);
        myMap.put('Perfume', 99.99);
        myMap.put('Shoe', 55.99);
        myMap.put('Sunglasses', 19.99);
        system.debug(myMap);
        
       List<String>tempKey =new List <String>();
          for(String key : myMap.keySet()){
            if(myMap.get(key)<10){
                tempKey.add(key);
            }
        }
        for(String key : tempKey){
            myMap.remove(key);
        }
        system.debug(myMap);
      */  
        
        
        
/*integer []myarray =new Integer []{10,15,23,34,45,76,45};
    for(integer index=0; index<myarray.size();index++){
system.debug(myarray[index]/2);
    }
system.debug(myarray);
 */       
        
        
        
        
        
        
        
        /*List<Integer>marks=new List<Integer>{45,56,78,98} ;
            integer sum=0;
        for(integer var  : marks){
            
        for   
        }
          system.debug(sum);  
       */     
        
         /*   List<Integer> list = new ArrayList<>();
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(10);
        list.add(9);
        int sum = 0;
        for (int i = 0; i < list.size(); i++)
            sum += list.get(i);
 
        System.out.println("sum-> " + sum);
            
*/            
            
            /*integer minValue =marks.get(0);
        for( integer var : marks){
            if(marks.get(var)<minValue){
               minValue=marks.get(var);
*/
            
     //   }
     //   }
        //system.debug(minValue);
        //for(integer i=0; i<marks.size();i++){
        //    if(marks.get(i)<minValue){
         //       minValue=marks.get(i);
         //   }
            
       // }
    // system.debug(minValue);
   
        
        
        
        
        
     
/*Set<String> country= new Set <String> {'Baku', 'new York','Los Angeles'};
List<String> RemovedCountry=new List<String>();

for(String each : country){
    if(each.length()>8){
        
       country.addAll(each.length()>8);
    }
}   
          system.debug(RemovedCountry);
  
*/        
        
        
        
 /*string text1='yoll academy';
       string text2='';
        integer count=0;
        while(count<12){
            text2+='*';
            count++;
            
                            
        }
        system.debug(text2);
     */ 
/* HW27       
Map<String,Decimal>managers=new Map<String,Decimal> ();  
Map<String,Decimal>executives=new Map<String,Decimal> (); 
        
managers.put('Bill', 15000.50);
managers.put('John', 25500.50);
managers.put('Elly', 22000.50);
        
executives.put('Taylor',22000.50);      
executives.put('Adam',18500.50);      
executives.put('Steve',13500.50);
        
system.debug((managers.keySet()).size());
system.debug((executives.keySet()).size());
        
List<String>employees=new List <String>();
employees.addAll(managers.keySet());
employees.addAll(executives.keySet());

system.debug('Managers : ' + managers);       
system.debug('Executives : ' + executives);       
system.debug('Emloyees : ' + employees);        
        
*/        
        
        
        
        
        
        
        
  //HW26//
        /*   Map<String,Decimal>myMap=new Map<String,Decimal>();
       myMap.put('Bread', 2.5);
       myMap.put('Milk', 5.5);
       myMap.put('Sugar', 3.75);
       myMap.put('Onion', 1.5);

        String item='Bread';
        myMap.remove(item);
        system.debug('Items to Purchase : ' + myMap.keySet());
        system.debug(myMap);
  */      
        
        
        
        
        
        
        
        
        
        
        
        
// HW25// 
/*  Map<String,String>firstName=new Map<String,String>{'First Name'=>'Urfana'};  
    Map<String,String>lastName=new Map<String,String>{'Last Name'=>'Teymurova'};  
    Map<String,String>myCity=new Map<String,String>{'City'=>'Istanbul'};  
     Map<String,String>myColor=new Map<String,String>{'Color'=>'Black'};  
  
     String first='First Name';
     String last='Last Name';
     String city='City';
     String color='Color';
        
      system.debug(firstName.get(first));  
      system.debug(lastName.get(last));  
      system.debug(myCity.get(city));  
      system.debug(myColor.get(color));  
*/
        
        
        
        
        
        
    //HW24// 
    /*Map<String,List<String>> myMap=new Map <String,List<String>>();
        List<String>L1=new List<String>{'Brian','Mia','Grayson'} ; 
        List<String>L2=new List<String>{'Jane','Layla','Eric'};
         myMap.put('Sales',L1);
         myMap.put('Support',L2);
        system.debug(myMap);
       */      

        
        
        
        
        
        
        
        
        
        
   //HW23//
   /*    Map<String,Integer>movies=new Map<String,Integer>();
      movies.put('Iron Man' , 2008);
      movies.put('Thor', 2011);
      movies.put('Doctor Strange' , 2016);
        system.debug(movies);
   */     
        
        
        
        
        
     //HW22// 
     /* Map<String,String>country = new Map <String,String>();
        country.put('Azerbaijan' , 'Baku');
        country.put('Turkiye' , 'Ankara');
        country.put('Russia' , 'Moscow');
        country.put('USA' , 'Washington DC');
         
        system.debug(country);
      */  

        
        
        
        
        
        
        
        
   //HW21??
   /*  Map<String,Integer>myMap=new Map <String,Integer>();
        myMap.put('Inji', 50);
        myMap.put('Ipek', 45);
        myMap.put('Fahmin',35);
        system.debug(myMap);
   */     
        
        
        
        
        
        
        
        
        
        
        
        
  // ERROR//   
 /*  Set<Integer>A=new Set <Integer>{1,2,3,4,5,6} ;
        Set <Integer>B=new Set <Integer>{5,6,7,8,9,10};
        Set<Integer>C=new Set<Integer>();
        Set<Integer>D=new Set<Integer>();
         A.retainAll(B);
        system.debug(A);
        B.retainAll(A);
        system.debug(A);
        */
        
        
        
        
        
        
   //HW19//
   /* Set<Integer>A=new Set <Integer>{1,2,3,5,6,7,9,10};     
    Set<Integer>B=new Set <Integer>{2,4,6,8,10};    
    Set<Integer>C=new Set<Integer>();
        
        system.debug('Set A = ' + A);
        system.debug('Set B = ' + B);
        
        A.retainAll(B);
        C.addAll(A);
        system.debug('Set C = ' + C);
*/
        
        
        
        
        
        
        
        
   //HW18   
   /*Set<Integer>A=new Set<Integer>{10,20,30};
        Set<Integer>B=new Set<Integer>{45,30,58};
        Set<Integer>C=new Set<Integer>();
        C.addAll(A);
        C.addAll(B);
        system.debug('Set A = ' + A);
        system.debug('Set B = ' + B);
        system.debug('Set C = ' + C);
*/
        
        
        
        
        
        
        
        
        
        
        
    //HW17//
    /*    Set<String>grocery=new Set<String>{'milk','sugar','bread','donut','pasta'} ;
        Set<String>stationary=new Set<String>{'glue','paper','pen','marker','sticker'};
        Set<String>items=new Set<String>();
        items.addAll(grocery);
        items.addAll(stationary);
        system.debug('Grocery Size = ' + grocery.size());
        system.debug('Stationary Size = ' + stationary.size());
        system.debug(items);
    */    
        
        
        
        
        
        
        
        
        
        
        
       ///HW16// 
       /*Set<List<Integer>> mySet= new Set <List<Integer>>();
        integer num1=2;
        integer num2=3;
        integer num3=4;
        
        List<Integer>listNum1=new List<Integer>{2,4,6,8,10,12,14,16,18,20};
        List<Integer>listNum2=new List<Integer>{3,6,9,12,15,18,21,24,27,30};
        List<Integer>listNum3=new List<Integer>{4,8,12,16,20,24,28,32,36,40};
        
        mySet.add(listNum1);
        mySet.add(listNum2);
        mySet.add(listNum3);
        system.debug(mySet);
        */
        
        
        
        
        
        
        
        
        
 //HW15//  
       /*  Set <List<Integer>> myNum= new Set <List<Integer>>();
        List<Integer> list1=  new List <Integer>{2,4,6,8,10,12,14,16,18,20};
        List<Integer> list2=  new List <Integer>{1,3,5,7,9,11,13,15,17,19};
        
        myNum.add(list1);
        myNum.add(list2);
        system.debug(myNum);
*/
        
        
        
        

   // HW 14//  
   /*  Set <String> mySet= new Set <String>();
        mySet.add('Emy');
        mySet.add('Anna');
        mySet.add('Richard');

        system.debug(mySet);
   */         
                  
        
        
        
        
        
        
        
        
        
        
     //HW M4 13//
     /*   List <Integer> mylist = new List <Integer> {10,25,30,20,50};
         myList.sort();
        
       integer count =0;
        for(integer each : myList){
            count++;
            
        }
        for(integer each : myList){
            system.debug(mylist.get(count-1));
            count--;
}
*/        
        
        
        
        
        
        
        
        
    //HW M4 12//
    /* List < Integer > marks = new List <Integer>{55,60,35,45,70,25,40};
      marks.sort(); 
        for(integer i =4; i<=marks.size()-1 ;i++){
            system.debug(marks[i]);
        }        
    */    
        
        
        
        
        
        
        
        
      //HW M4 11//
      /*  List <String> myFriends = new List <String>{'Ruba', 'Naza'};
            system.debug(myFriends);
        List<String> myTeammates =new List <String>{'James', 'Brian', 'Steve'};
            myFriends.addAll(myTeammates);
            myFriends.sort();
            system.debug(myFriends);
      */  
        
        
        
        
        
        
        
        
      //HW M4 10//
      /*  List <Integer> myList1 = new List <Integer>();
        List<Integer> myList2 =new List <Integer>();
        for(integer i=1; i<=10;i++){
        myList1.add(i*2) ; 
        }
        for(integer j=1; j<=10; j++){
            myList2.add(j*3);
        }
        system.debug('First List = ' + myList1);
        system.debug('Second List = ' + myList2);
        myList1.addAll(myList2);
        system.debug('Updated First List = ' + myList1);
        myList1.sort();
        system.debug('Updated List After Sort = ' + myList1);
      */      
        
        
        
        
        
        
        
       //HW M4 9//
       /* List <Integer> myList = new List <Integer> {5,10,15,20,25,30,35};
        system.debug('Original = ' + myList);
        myList.add(4,50);
        system.debug('Adding 50 = ' + myList);
        myList.set(3,100);
        system.debug('Updating 3rd Index = ' + myList);
        myList.remove(0); 
        system.debug('Removing First = ' + myList);
        myList.remove(6);
        system.debug('Removing Last = ' + myList);
       */ 
        
        
        
        
        
        
        
          
      /*   HW   List<String> names = new List<String>{'Amit', 'Sparsh', 'Vicky', 'Reshid', 'Raisa', 'Vlad'};
                   
        // Position : Represents position of any element (Counting): Always starts with 1
        Integer position = 1; // Index is always 1 less than the value of the position for the same element
        Integer index = position - 1;

        System.debug('Names at position # '+position+' = '+names.get(index));
*/
        
        
        
          
      /*Homework 60//
         integer num = 563;
        integer originalNum = num;
        integer reverseNumber = 0;      //563
        integer firstDigit = Math.mod(num, 10); //--> 3
        reverseNumber = firstDigit*100; //--> 300
        num = num/10;     // --> 56
        integer seconDigit = Math.mod(num, 10); //--> 6
        reverseNumber = reverseNumber + seconDigit*10; //--> 300+60=360
        integer thirdDigit=num/10;
        reverseNumber=reverseNumber+thirdDigit;
      
         system.debug(reverseNumber);
      
        Integer i;
        for(i = 2; i < num; i++) {
            if(Math.mod(num, i) == 0){     
                break;
            }
            for(i=2;i<reverseNumber;i++){
                if(Math.mod(reverseNumber, i)==0){
                    break;
                }
            }
        }
        if(i == originalNum && i==reverseNumber){
            System.debug(originalNum+ ' and ' + reverseNumber + ' are EMIRP numbers');
        }
        else{
            System.debug(originalNum+ ' and ' + reverseNumber + ' are not EMIRP numbers');
        }
     */
      
      
        
        
        
        
        
        
        
        
        
        
        
        
         /* Hw     integer size =7 ;
        Integer [] myarray = new Integer[size];
        
     
       for(Integer index=0; index<7; index++){             // assign values in array
            myarray[index] = index+1;
            System.debug(myarray[index]);
        }

       // for(Integer index=0; index<7; index++){             // print values of array
       //     System.debug(myarray[index]);
      
         //       }      
  */
        
        
        
        
        
        
        
        
         /* Odd numbers
      Integer [] myarray = new Integer [5];
      integer index=0;
      integer start=12;
      
      for(integer i=start; ;i++){
          if(Math.mod(i, 2)!=0){
              myarray[index]=i;
              index++;
          }
          if(index==5){
              break;
          }
      }
      
      for(index=0; index<5; index++){
          system.debug(myarray[index]);
      }
      */
      

        
        
        
        
    /*    String text ='10/06/2010';
        String month=text.substringBefore('/');
       // system.debug(month);
        switch on month{
            when '01'{
                system.debug('January');
            }
            when '02'{
                system.debug('February');
            }
            when '03'{
                system.debug('March');
            }
            when '04'{
                system.debug('April');
            }
            when '05'{
                system.debug('May');
            }
            when '06'{
                system.debug('June');
            }
            when '07'{
                system.debug('July');
            }
            when '08'{
                system.debug('August');
            }
            when '09'{
                system.debug('September');
            }
            when '10'{
                system.debug('October');
            }
            when '11'{
                system.debug('November');
            }
            when '12'{
                system.debug('December');
            }
            when else {
                system.debug('ERROR: Invalid Month');
            }
        }
     */   
        
        
        
        
        
        
        
        
        
 /*       String month='January';
        switch on month{
            when 'January'{
                system.debug('31');
            }
             when 'February'{
                system.debug('28');
            }
            when 'March' {
                system.debug('31');
            }
             when 'April'{
                system.debug('30');
            }
             when 'May'{
                system.debug('31');
            }
             when 'June'{
                system.debug('30');
            }
             when 'July'{
                system.debug('31');
            }
             when 'August'{
                system.debug('31');
            }
             when 'September'{
                system.debug('30');
            }
             when 'October'{
                system.debug('31');
            }
            when 'November'{
                system.debug('30');
            }
            when 'December'{
                system.debug('31');
            }
        }
      */
        
        
        
        
        
        
        
        
        
     /*   integer num =7;
        switch on num {
            when 1,3,5,7,9{
                system.debug('Odd number');
            }
            when 2,4,6,8{
                system.debug('Even number');
            }
            when else{
                system.debug('ERROR: Value should be between 1 to 9');
            }
        }
        */
        
        
        
        
        
        
        
        
 /*   integer month =5;
        switch on month{
            when 1,2,3{
                system.debug('First quarter');
            }
            when 4,5,6{
                system.debug('Second quarter');
            }
            when 7,8,9{
                system.debug('Third quarter');
            }
            when 10,11,12{
                system.debug('Fourth quarter');
            }
            when else {
                system.debug('ERROR: Invalid month of the year');
            }
        }
        */
     
        
   /*     decimal basicSalary=17000;
        decimal ta;
        decimal da;
        decimal hra;
        decimal totalSalary;
        
         system.debug('Basic Salary = ' + basicSalary);  
        if(basicSalary>25000){
            ta=basicSalary * 0.1;
            da=basicSalary *0.8;
            hra=basicSalary * 0.1;
            totalSalary =basicSalary + ta + da+ hra;
            
            system.debug('Travel Allowance = ' + ta);
            system.debug('Dearness Allowance = ' + da);
            system.debug('House Rent Allowance = ' + hra);
            system.debug('Total Salary = ' + totalSalary);
        }
        else if (basicsalary>=10000 && basicSalary<=25000) {
            ta=basicSalary * 0.12;
            da=basicSalary *0.85;
            hra=basicSalary * 0.15;
            totalSalary =basicSalary + ta + da+ hra;
            
            system.debug('Travel Allowance = ' + ta);
            system.debug('Dearness Allowance = ' + da);
            system.debug('House Rent Allowance = ' + hra );
            system.debug('Total Salary = ' + totalSalary);
        }
        else if (basicSalary<10000){
            ta=basicSalary * 0.15;
            da=basicSalary *0.9;
            hra=basicSalary * 0.2;
            totalSalary =basicSalary + ta + da+ hra;
            
            system.debug('Travel Allowance = ' + ta);
            system.debug('Dearness Allowance = ' + da);
            system.debug('House Rent Allowance = ' + hra );
            system.debug('Total Salary = ' + totalSalary);
            
        }
        
       */ 
        
        
        
        
      /*Write a program and create decimal variables, basicSalary, ta, da, hra and totalSalary.
Assign a value to basicSalary.
Calculate totalSalary as sum of basicSalary, ta, da and hra.
Print the basicSalary, ta, da, hra and totalSalary.
The ta, da and hra are calculated as follows:
 */ 
        
        
        
        
        
        
        
        
   
     /*   integer age =19;
        integer grade =80;
        boolean computerLitrate=true;
        
        if(age>=18 && grade>=75 && true){
            system.debug('Congratulations! You are Selected');
        }  
        else if (age<18 && grade>=75 && true){
            system.debug('Sorry! Out of Round 1');
        }
        else if (age>=18 && grade<75 && false){
            system.debug('Sorry! Out of Round 3');
        }
        
       */ 
        
        
        
        
/*Write a program and create two integer variables ‘age’ & ‘grade’ and one boolean variable as ‘computerLitrate’.
Assign values to these variables.
These values will be used to check whether the candidate will clear a certain round or not.
To clear Round 1 Age should be greater than or equal to 18 and less than or equal to 60.
To clear Round 2 Grade should be greater than or equal to 75.
To clear Round 3 a candidate should be computer literate or value of computer literate should be true.
A candidate who clears all the Rounds will be Selected.
 */       
        
        
        
        
        
        
   /*   integer grade = 101;
        
        if(grade>=95 && grade<=100){
            system.debug('A');
        }
       else if(grade>=90 && grade<=94){
            system.debug('B');
        }
      else  if(grade>=85 && grade<=89){
            system.debug('C');
        }
     else   if(grade>=80 && grade<=84){
            system.debug('D');
        }
      else  if(grade>=75 && grade<=79){
            system.debug('E');
        }
       else if(grade>0 && grade<75){
            system.debug('Student Reproved');
        }
        else{
            system.debug('ERROR: Please provide valid grade');
        }
        */
        
        
        
        
        
    /*   integer A =15;
       integer B= 9;
        
        if(A==B){
            system.debug('Both numbers are same');
        }
           if(A>B) {
               system.debug('First number is greater than second number');
           }
        else{
            system.debug('Second number is greater than first number');
        }
        
   */     
        
 
        
        
   /*     String A = 'Miami';
        String B ='Chicago';
        String C='Vancouver';
        
        if(A.length()>B.length() && A.length()>C.length()){
            system.debug('Largest string = ' + A);
        }
        else if (B.length()>A.length() && B.length()>C.length()){
            system.debug('Largest string = ' + B );
        }
        else
            system.debug('Largest string = ' + C);
        
  */      
        
  
        
        
    /*   integer num=275;
       String str=String.valueOf(num);
        
        if(str.length()==1){
            system.debug(num + ' is single digit number');
        }
        else if (str.length()==2){
            system.debug(num + ' is two digits number');
        }
        if(str.length()==3){
            system.debug(num + ' is three digits number');
        }
        else
            system.debug(num + ' more than three digits number');
        
  */      
        
        
        
        
        
        
        
        
         
     /*  integer quantity=3000;
        decimal rate = 4.5;
        decimal total=quantity*rate;
       
        system.debug('Total price is : ' +total );
        double discount=total*0.25;
        double discount2=total*0.1;
        
        if(total>10000){
            system.debug('Discount is ' + discount);
        }        
        else
            system.debug('Discount is : ' + discount2);
        
        double netPrice=total-discount;
        
        system.debug(netPrice);

     */   
        
        
        
        
        
        
        
        
        
        
        
        
        
   /*     String A='Baku';      
        String B='Istanbul';
        String C ='Moscow';
        
       integer A1=A.length();
       integer B1=B.length();
       integer C1=C.length();
      
       integer smaller=A1<B1 && A1<C1 ?A1:B1;
       integer smaller2=B1<A1 && B1<C1 ? A1:C1;
       integer smallest =smaller<smaller2 ? smaller : smaller2;
        
       system.debug(A);
       system.debug(C);
       system.debug(B); 
        */
        
        
        
        
             
        
     
/*Write a program and create one integer variable, ‘quantity’, and one decimal variable ‘rate’.
 *  Assign values to these variables.
Calculate the total price and net price, where the total price is the product of quantity and rate.
The net price will be the total price - discount.
The discount will be 25% of the total price if the total price is greater than 10000, 
else discount will be 10% of the total price. 

Print the total price, discount, and net price.
For e.g., If Quantity = 1000, Rate = 3.5, then the output of the program should be:
Total Price = 3500.00
Discount = 350.00
Net Price = 3150.00For e.g., If Quantity = 2000, Rate = 5.5, then the output of the program should be:
Total Price = 11000.00
Discount = 2750.00
Net Price = 8250.00
      */  
        
        
        
        
        
        
        
        
        
        
        
        
   /*     integer A =5;
        integer B=9;
        integer C =13;
        integer D=4;
        integer sum = A+B+C+D;
        
        if(Math.mod(sum, 2) ==0){
            system.debug('Sum of the variables is an Even number');   
        }
        else
            system.debug('Sum of the variables is an Odd number');
     */   
        
        
 //  Write a program and create 4 integer variables, A, B, C, and D.
//Assign any values to these variables.
//Print whether the sum of these variables is Even or Odd.//     
        
        
        
        
        
        
   /*  integer A=15;
     integer B=30;
        
        if(A>B){
            system.debug('bigger number is :' + A);
            system.debug('smaller number is : ' + B);
        }    
       else
           system.debug('Bigger number is : ' + B);
           system.debug('Smaller number is : ' + A);
        
    */    
        
        
        
//Write a program and create two integer variables, A and B.
//Assign any values to these variables. 
//Print the smaller number and the bigger number of the two.        
        
        
        
        
 /*   integer num =-3;
        if(num>0){
          system.debug(num + ' is a positive number ');  
        }
        else
            system.debug(num + ' is a negative number');
  */      
        
        

        
       
     /*      String A='California';    
           String B='Texas';        
           String C='Florida';      
                              
        
        if(A.length()<B.length() && A.length()<C.length()){
            system.debug('A');
        }  
        else if(B.length()<A.length() && B.length()<C.length()){
            system.debug('B');
        }
        else
            system.debug('C'); 
        
      */  
        
        
        
        
        
        
        
        
/*       string word1 = 'Hello';
        string word2= 'Salesforce';
        string word3 = 'Apex';
        
        string longerWord1= word1.length() > word2.length() && word1.length() > word3.length() ? word1 : word2;
        string longerWord2= word1.length() > word2.length() && word1.length() > word3.length() ? word1 : word3;
        
        String longestWord = longerWord1.length() > longerWord2.length() ? longerWord1 : longerWord2;
        
        System.debug('Text 1 = ' + word1);
        System.debug('Text 2 = ' + word2);
        System.debug('Text 3 = ' + word3);
        System.debug('Longest Text = ' + longestWord);
 
 */       
    
    
    /*Write a program and create 3 String variables A, B and C. 
Assign these variable with any values.
Use if statements to print the smallest string in relation to their length.

For e.g, If the 3 strings are ‘California’, ‘Texas’ and ‘Florida’ respectively, then the output of the program is:
Texas    
        
 */       
        
        
        
        
        
        
        
        
        
/*  Integer a=5;
  Integer b=3;
  integer sum=a+b;
        if(sum>10){
            system.debug('Sum of a and b is greater than 10');
        }
*/



        
        
        
   /*  String name1='Ali';            
     String name2='Dave';            
     String name3='Samantha';         
     String userInput=name3;
     integer num=userInput.length();
        
        if(num<=4){
            system.debug('User Input Name = ' + userInput);
        }
        else{
            system.debug('User Input Name = ' + userInput.substring( num-4));
        }
   */
        
        
        
        
        
/*Write a program in Apex and create three String variables  ‘name1’, ‘name2’ and ‘name3’. 
Assign three names, one in each variable, lets say: ‘Samantha’, ‘Dave’ and ‘Ali’.
Create a String variable named ‘userInput’ and assign any of the three variables to it.
userInput = name1/name2/name3;
Print the name in the userInput as well as last four characters of the name. Print the whole name in case the name is having less than or equal to four characters. 
Print the output as shown below*/









        
      
/*Sample Output 1:
User Input Name = Ali
Last Four Characters = Ali
Sample Output 2:
User Input Name = Dave
Last Four Characters = Dave
Sample Output 3:
User Input Name = Samantha
Last Four Characters = ntha  
 */       
        
        
        
        
        
        
        
        
        
     /*   String text1= 'Hello', text2='Apex',text3='Salesforce';
        integer a=text1.length();
        integer b=text2.length();
        integer c=text3.length();
        integer largest=
        
        
        
       system.debug('Text 1= ' + text1);
       system.debug('Text 2= ' + text2); 
       system.debug('Text 3= ' + text3);
       */ 
      
        
        
       // Text 1 = Hello
       // Text 2 = Salesforce
      //  Text 3 = Apex
      //  Longest Text = Salesforce
        
      /*  Integer a=4;
        Integer b = 5;
        Integer c = ++a + b--;                      // after b becomes -1=4, a=5, c=10
        Integer d = a++ + ++b;                     // after a becomes +1=6, b=5 , d=10
        System.debug(a+','+b+','+c+','+d);         //  Statement1--> a=6,b=5;c=10 d=10                  
        Integer e = a-- + --b + --c + d--;         //  after a become -1=5,b=4, c=9, after d becomes -1=9 ,e=29
        System.debug(a+','+b+','+c+','+d+','+e);  //   Statement2 --> a=5,b=4,c=9,d=9,e=29                                  
        Integer f = a++ + ++b + ++c + d++;        //   after a becomes +1=6,b=5,c=10,after d becomes +1=10,f=29 
        System.debug(a+','+b+','+c+','+d+','+f);  //   Statement3 --> a=6,b=5,c=10,d=10,f=29      
     */   
        
        
      
        
    /*  Integer a =5;
      integer b =10;
        
      integer bigger = a>b ? a : b;
      integer smaller =b>a ? a : b;
      integer result=bigger/smaller;
      system.debug('Value 1 = ' + smaller);
      system.debug('Value 2  = ' + bigger );
      system.debug('Result of Division = ' + result );
  */      
              
        
        
        
        
 //Write a program in Apex.
//Create two integer variables and assign values to them.
//Create a third variable and store the result of the division of the two variables.
//Make sure to divide the bigger number by the smaller number.
//Print the result as shown below.
//Sample Output:
//Value 1 = 5
//Value 2 = 10
//Result of Division = 2

        
        
        
        
        
     /*  Integer X =20;
       Integer Y =25;
       Integer Z =100;
        
       system.debug('X is the largest number = ' + (X>Y && X>Z));
       system.debug('Y il the largest number = ' + (Y>X && Y>Z)); 
       system.debug('Z is the largest number = ' + (Z>X && Z>Y)); 
        
     */   
        
        
       
        
        
        
        
        
        
        
        
        
    /*  decimal length =1.8;
      decimal width  =2.7;
      decimal area=length * width;
        
        
      system.debug('Length ' + length);
      system.debug('Width ' + width);
      system.debug('Area ' + area.setScale(1) );
    */    
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
     
   /*  String sentence='CRM helps companies to manage their relationship with their customers'  ;
     String text1 ='manage';
     string text2 ='customers';
        
      String subSentence=sentence.substringAfter('to ') ; 
      system.debug(subSentence);  
      system.debug('word customers comes before word manage : '  +  subSentence.startsWith(text2));
  */                 
        
       
        
        
        
        
    }
    
}