public class ListPrograms {
    public static void show(){
        
        
        /*  Map<String, String> countryCurrency = new Map<String, String>();
        countryCurrency.put('United States', 'USD');
        countryCurrency.put('Canada', 'CAD');
        countryCurrency.put('Azerbaijan', 'AZN');
        countryCurrency.put('India', 'INR');
        countryCurrency.put('Pakistan', 'PKR');
        System.debug(countryCurrency);

/*
{Azerbaijan=AZN, Canada=CAD, India=INR, Pakistan=PKR, United States=USD}
*/
       /*   Map<Integer, String> students = new Map<Integer, String>();

        students.put(1, 'Peter');
        students.put(2, 'James');
        students.put(3, 'Chris');
        students.put(2, 'Harry');
        students.put(4, 'Harry');

        System.debug(students);

/*
{1=Peter, 2=Harry, 3=Chris, 4=Harry}
*/
        
/*        Set <Integer> A=new Set <Integer> {1,3,5,7,9,11} ;
        Set <Integer> B=new Set <Integer> {1,9,11} ;
 
            if(A.containsAll(B)){
                system.debug('Set A contains B');
            }
        else
            system.debug('Set A does not contains B');
        
        
    */    
        
        
        
        
/*        List<Integer> mylist1 = new List<Integer>{10, 3, 4, 7, 12, 17, 16, 15, 4, 3, 12, 21, 13, 17};
        List<Integer> mylist2 = new List<Integer>{1,2,3};

        Set<Integer> myset = new Set<Integer>();    // Create a Set to hold collection of Integer
        myset.addAll(mylist1);                       // Adding all the elements of mylist to the set
        myset.addAll(mylist2);                       // Adding all the elements of mylist to the set
        
        System.debug(myset);

        Set<List<Integer>> setOfList = new Set<List<Integer>>();    // Create a Set to hold collection of lists
        setOfList.add(mylist1);                                      // Adding the list to the set
        setOfList.add(mylist2);                                      // Adding the list to the set
        
        System.debug(setOfList);
*/
/*
{1, 2, 3, 4, 7, 10, 12, 13, 15, 16, ...}
{(10, 3, 4, 7, 12, 17, 16, 15, 4, 3, ...), (1, 2, 3)}
*/
        /*List<Integer> mylist = new List<Integer>{10, 3, 4, 7, 12, 17, 16, 15, 4, 3, 12, 21, 13, 17};

        Set<Integer> myset = new Set<Integer>();
        myset.addAll(mylist);
        
        System.debug(mys
        */
        
        
        
        
        
        
         /* List<Integer> mylist1 = new List<Integer>{2, 4, 6, 8};
        List<Integer> mylist2 = new List<Integer>{1, 3, 5, 7};

        Set<List<Integer>> setOfList = new Set<List<Integer>>();

        setOfList.add(mylist1);
        setOfList.add(mylist2);

        System.debug(setOfList);
*/

        
        
        /*
{(2, 4, 6, 8), (1, 3, 5, 7)}
*/
        
    /*    Set<Integer> mySet1 = new Set<Integer>();
        mySet1.add(20);
        mySet1.add(30);
        mySet1.add(10);
        mySet1.add(10);
        mySet1.add(20);
        System.debug(mySet1);

*/



     /*   Set<String> mySet2 = new Set<String>{'C', 'C++', 'Java', 'Apex', 'HTML', 'C', 'c'};

        System.debug(mySet2); 
        
    */    
        
        
        
        
        
        
        
        
    /*   Set<Integer>mySet=new Set <Integer> {1,2,3,4,5,7,9,13,45,76} ;
      system.debug(mySet); 
   */     
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
}