public virtual with sharing class ParentClass {
    
   

Integer var1 ;
String var2 ;
List<Integer>list1=new List<Integer>();


public void setVar1(Integer var1){
    this.var1=var1;
}

public void setVar2(String var2){
    this.var2=var2;
}

public void setList1( List <Integer> list1){
    this.list1=list1;
} 


public integer getVar1(){
    return var1;
}

public String getVar2(){
    return Var2;
}

    public List<Integer> getList1(){
    return list1;
    }





    }