public with sharing class Calculator2 {
    Integer a;
    Integer b;

    public void accept(Integer num1, Integer num2){
        a = num1;
        b = num2;
    }

    public integer getSummation(){
        return a+b;
    }

   public integer getDifference(){
    return a-b;
   }

   public integer getProduct(){
    return a*b;
   }

    public integer getQuotient(){
        return a/b;
    }














}