public class IfStatementPractice {
    public static void show(){
      
        
 /*          boolean isTired = false;
  *           boolean isHungry=true;
        
        	System.debug('I wake up');
if(isHungry){
        	System.debug('I eat breakfast');
}
        	System.debug('I study');
        
        	if(isTired){
        		System.debug('I take a nap');
        	}
        
        	System.debug('I go for a walk');
        	System.debug('I go to sleep');
        
*/
        
     /*   System.debug('I wake up');
        	System.debug('I eat breakfast');
        	System.debug('I study');
        
        	if(2>5){		//this is the condition part. It must always result in boolean value.
        		System.debug('I take a nap'); //statement will execute only if condition is true
                System.debug('I wake up from nap');
            
            
            }
        
        	System.debug('I go for a walk');
        	System.debug('I go to sleep');
  
     */
        
     /*   	String userEnteredPassword='wbc123';
        	String actualPassword='abc123';
        
        
        	System.debug('Hello, let me check if you have entered correct password');
			
        if(userEnteredPassword.equals(actualPassword)){
            System.debug('Welcome');
            //inside the scope
        }
        //outside the scope
           	System.debug('Thank you');
        */
        
     /*   integer minimumAge = 18;
        integer customerAge=20;
        boolean hasTickets = false;
        
        if(customerAge>=minimumAge || hasTickets){
            System.debug('Allow customer to enter');
        }
      */
        
        

        
       integer a = 3;
        integer b = 15;
        integer c = 20;
        integer d = 3;
        
       /* 
        if(Math.mod(a , 2) == 0){
            System.debug('a is even Number');
        }
        
        if(Math.mod(b, 2) == 0){
            System.debug('b is even Number');
        }
        
        if(Math.mod(c, 2) == 0){
            System.debug('c is even Number');
        }
        
        if(Math.mod(d, 2) == 0){
            System.debug('d is even Number');
        }
    */    
     /*   if(Math.mod(a , 2) != 0){
            System.debug('a is odd Number');
        }
        
*/
         /*     boolean isTired = false;
        	boolean isHungry=true;	
        	boolean isFridgeFull=true;	
        
        	System.debug('I wake up');
        
        	if(isFridgeFull){
       		     System.debug('I eat breakfast');
        	}
        	else{
            	System.debug('Do grocery shopping and fill up the fridge');
        	}
        	
        	System.debug('I study');
*/
        
  /*     String userEnteredPassword='abc123';
        String actualPassword='abc123';
        
        
        System.debug('Hello, let me check if you have entered correct password');
			
        if(userEnteredPassword.equals(actualPassword)){
            System.debug('Welcome');
        }
        else{
            System.debug('Sorry you intered incorrect password');
        }
          
        //anything below which is outside of the scope gets executed regardless of the if statements
        System.debug('Thank you');
        */
        
        /*
          integer a = 20;
        
        if(a>10)
        System.debug('h');	//condition is true --> h gets printed
        else
        System.debug('j');
        System.debug('k');	//this will get printed regardless of the condition. Because it is not part of the scope.
        
        */
        
        
        
        
        
        
        
        
        



        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
    
    
    
    
    
    
    
    
    
    
    
    

}