public class MyClass1 {
    public static void count(){
   /*    
   integer a;
   integer b;
    a=20;
    b= 30;
    
   system.debug(a);
   system.debug(b);
    integer c=a+b;
    system.debug(c);
        */
        
       String myName='Emily';
       Integer myAge=24;
       Integer myHeight=5;
       Integer myHeight1=50;
        String city='Chicago';
        
        system.debug('Hello my name is : ' + myName); 
        system.debug('I am ' + myAge +  ' years old');
        system.debug('I am ' + myHeight + ' feet ' + myHeight1 + ' inches tall');
        system.debug('I am from ' + city);
        
        
        
        
  }
 }