public class PracticeOne {

   public static void show(){
       /*
       
       integer numberOfYourpencils=10;
       system.debug(numberOfYourPencils);
        
      integer numberOfMyPencils=5;
       system.debug(numberOfMyPencils);
       integer numberOfOurPencils=numberOfYourPencils + numberOfMyPencils;
       system.debug(numberOfOurPencils);
       
       */
        
       
       //integer num=20;
       //system.debug(num);
       
        
       //Long myNum=123567589339L;
       //system.debug(myNum);
       
       //Double height=5.9;
       //system.debug(height);
       
       // integer num1=20;
        //integer num2=6;
       
       //system.debug(num1 +num2);    //26
       //system.debug(num1 -num2);    //14
       //system.debug(num1*num2);     //120
      // system.debug(num1/num2);     //3.33333   ---> but we get 3,
       
      // system.debug(20.0/6.0);      //3.33333
      
       /*
       integer a=10;
       double b=2.5;
       integer c=30;
       integer d=7;
       
       //system.debug(a+b);
       //system.debug(a*c);
       
       a=d;
       system.debug(a+c);
       system.debug(d+c);
       
       integer f= a+c;   //f=7+30
       a=a+c;            // 37
       system.debug(a+c);
       
       double e =a/d;  //67/7.0
       //system.debug(e);
       
       
       integer apple=10;
       integer cranberry=30;
       integer pineapple=55;
       integer orange=22;
       
       system.debug(apple+orange);   //32
       cranberry=apple*orange;       //220
       system.debug(pineapple*apple);//550
       system.debug(apple*cranberry);//2200
       
       
       double result1 = 2.0/3.0;
       decimal result2=2.0/3.0;
           
           //system.debug('double result is: ' + result1);
          // system.debug('decimal result is: ' + result2);
       
       
       
      decimal num = 25.252726 ;
       system.debug('original value of the num is: ' + num); 
       system.debug('This version with 2 decimal points' +num.setScale(2) );
       system.debug('This version with 3 decimal ' + num.setScale(3));
       system.debug(num);
       num=num.setScale(2);
       system.debug(num);
       
       
       integer age =29;
       system.debug('I am '  + age + ' years old ');
       
       Long p =7977148450L;
       system.debug('Currently there are than ' + p + ' people in the world');
       
       
       double height=165.2;
       system.debug('I am ' +height + ' cm long');
       
       
    */   
      
       
       
     /*  
       //boolean flag=true;
       //system.debug(flag);
       
       String sentence='Hello students'  ;
       system.debug(sentence);
       
       String name='urfana';
       String welcomeMessage='Hi.My name is: ';
       system.debug(welcomeMessage + name);
       */
       
       
       
       /*
       Integer a=10;
       Integer b=20;
       String c='20';
       
       system.debug(a+b);      //30      math addition
       system.debug(a+c);      //1020   concatination
       
       //integer d=a+c;    //will not work.bec end result is string
       string d=a+c;     //integer+string. --> string
           */
       
       
       
        /* 
        Date bestDay=Date.today();
        system.debug(bestDay);       
       
        Date dateOfBirth=Date.newInstance(1993, 01, 03);
        system.debug('Date of birth of user : ' + dateOfBirth);
       */
       
         
       
       /*
       DateTime rightNow=DateTime.now();
       system.debug(rightNow);
   
       DateTime timeOfIncident=DateTime.newInstance(2022, 10, 4, 23, 30, 50);
       system.debug('The incident happened at : ' + timeOfIncident);
       */
       
       
       
       /*
       string name='Urfana';
       boolean sport=true;
       boolean music=true;
       
       system.debug('Hello Apex , My name is : ' + name );
       system.debug('I love sport ' + sport);
       system.debug('I love music ' + music);
       
       
       Date appDate=Date.newInstance(2022, 11, 14);
       DateTime entranceTime=DateTime.newInstance(2022, 11, 14, 12, 40, 30);
       system.debug('Appointment date is : ' + appDate);
       system.debug('Entrance to building date and time : ' + entranceTime);
       
      */ 
        
        
    }
}