public class SwitchPractice {
    public static void show(){
        
        
        
         Integer userEnteredDay = 5;
        
  /*      switch on userEnteredDay{
            when 1{
                System.debug('Monday');
            }
            when 2{
                System.debug('Tuesday');
            }
            when 3{
                System.debug('Wednesday');
            }
            when 4{
                System.debug('Thursday');
            }
            when 5{
                System.debug('Friday');
            }
            when 6{
                System.debug('Saturday');
            }
            when 7{
                System.debug('Sunday');
            }
            when else{
                System.debug('Invalid week day selection');
            }
            
      */
        
        
   /*   	String password = 'watermelon';
        	
        	switch on password{
                when 'apple'{
                    System.debug('Correct Password. Welcome');
                }
                when else{
                    System.debug('Incorrect Password.');
                }
      	  	} 
  */
        
    /*    integer studentGrade = 65;
        	
        if(studentGrade<=50){
            System.debug('F');
        }
        else if(studentGrade<=60){
            System.debug('D');
        }
        else if(studentGrade<=70){
            System.debug('C');
        }
        else if(studentGrade<=80){
            System.debug('B');
        }
        else{
            System.debug('A');
        }
        */
   /*
   integer studentGrade = 85;
        	
        if(studentGrade>=90){
            System.debug('A');
        }
        else if(studentGrade>=80){
            System.debug('B');
        }
        else if(studentGrade>=70){
            System.debug('C');
        }
        else if(studentGrade>=60){
            System.debug('D');
        }
        else{
            System.debug('F');
        }
*/
        /*
          integer studentGrade = 63;
        studentGrade = studentGrade/10;		//6
        

                    }        switch on studentGrade{
            when 9 {
                System.debug('A');
                    }
            when 8 {
                System.debug('B');
                    }
            when 7 {
                System.debug('C');
            when 6 {
                System.debug('D');
                    }
            when else {
                System.debug('F');
                    }
        }
*/
        
        Integer num=5;
         switch on num{
            when 0 {
                System.debug('Zero');
                    }
            when 1 {
                System.debug('One');
                    }
            when 2 {
                System.debug('Two');
            }
         when 3 {
                System.debug('Three');
                    }
            when 4 {
                System.debug('Four');
                    }
            when 5 {
                System.debug('Five');
            }
         when 6 {
                System.debug('Six');
                    }
            when 7 {
                System.debug('Seven');
                    }
            when 8 {
                System.debug('Eight');
            }
        when 9 {
                System.debug('Nine');
            }
                         when -1,-2,-3,-4,-5,-6,-7,-8,-9 {
                System.debug('ERROR:Invalid Single Digit Positive Number');
                    }
         
             when else{
                 system.debug('ERROR: Invalid Digit Positive Number');
             }
             
        
        
        
         }
        
        
        
        
        
        
        
        
        
        
        

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
            
    }     
    }